// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin listResource
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/list"
	listschema "github.com/hashicorp/terraform-plugin-framework/list/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
)

var (
	_ list.ListResource              = &IPv6LocalPoolResource{}
	_ list.ListResourceWithConfigure = &IPv6LocalPoolResource{}
	_ resource.ResourceWithIdentity  = &IPv6LocalPoolResource{}
)

func NewIPv6LocalPoolListResource() list.ListResource {
	return &IPv6LocalPoolResource{}
}

// IPv6LocalPoolListConfig holds the filter configuration for a IPv6 Local Pool list block.
type IPv6LocalPoolListConfig struct {
	Device types.String `tfsdk:"device"`
}

// IPv6LocalPoolIdentity holds the identity attributes that uniquely identify a IPv6 Local Pool instance.
type IPv6LocalPoolIdentity struct {
	Device types.String `tfsdk:"device"`
	Name types.String `tfsdk:"name"`
}

func (r *IPv6LocalPoolResource) IdentitySchema(_ context.Context, _ resource.IdentitySchemaRequest, resp *resource.IdentitySchemaResponse) {
	resp.IdentitySchema = identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"device": identityschema.StringAttribute{
				OptionalForImport: true,
			},
			"name": identityschema.StringAttribute{
				RequiredForImport: true,
			},
		},
	}
}

func (r *IPv6LocalPoolResource) ListResourceConfigSchema(_ context.Context, _ list.ListResourceSchemaRequest, resp *list.ListResourceSchemaResponse) {
	resp.Schema = listschema.Schema{
		Attributes: map[string]listschema.Attribute{
			"device": listschema.StringAttribute{
				MarkdownDescription: "A device name from the provider configuration.",
				Optional:            true,
			},
		},
	}
}

func (r *IPv6LocalPoolResource) List(ctx context.Context, req list.ListRequest, resp *list.ListResultsStream) {
	var config IPv6LocalPoolListConfig
	diags := req.Config.Get(ctx, &config)
	if diags.HasError() {
		resp.Results = list.ListResultsStreamDiagnostics(diags)
		return
	}

	if r.data == nil {
		resp.Results = list.ListResultsStreamDiagnostics(diag.Diagnostics{
			diag.NewErrorDiagnostic("Provider not configured", "The provider has not been configured. Ensure the provider block is set up correctly."),
		})
		return
	}

	device, ok := r.data.Devices[config.Device.ValueString()]
	if !ok {
		resp.Results = list.ListResultsStreamDiagnostics(diag.Diagnostics{
			diag.NewErrorDiagnostic("Invalid device", fmt.Sprintf("Device '%s' does not exist in provider configuration.", config.Device.ValueString())),
		})
		return
	}

	if !device.Managed {
		resp.Results = list.NoListResults
		return
	}

	if device.Protocol != "restconf" {
		resp.Results = list.ListResultsStreamDiagnostics(diag.Diagnostics{
			diag.NewErrorDiagnostic(
				"Unsupported Protocol",
				fmt.Sprintf("The terraform query command is only supported with the RESTCONF protocol. Device '%s' uses NETCONF. Configure the provider with protocol = \"restconf\".", config.Device.ValueString()),
			),
		})
		return
	}

	// Build a helper struct to derive the parent collection path.
	// List-config attributes (path-embedded context) are set from config;
	// leaf key attributes are left at zero values so getPathShort() produces
	// the correct parent collection URL without a key predicate.
	var pathHelper IPv6LocalPool
	pathHelper.Device = config.Device
	collectionPath := pathHelper.getPathShort()
	lastElement := helpers.LastElement(pathHelper.getPath())

	res, err := device.RestconfClient.GetData(collectionPath)
	if err != nil {
		resp.Results = list.ListResultsStreamDiagnostics(diag.Diagnostics{
			diag.NewErrorDiagnostic("Client Error", fmt.Sprintf("Failed to list %s objects (%s), got error: %s", "ipv6_local_pool", collectionPath, err)),
		})
		return
	}
	if res.StatusCode == 404 {
		resp.Results = list.NoListResults
		return
	}

	items := res.Res.Get(lastElement).Array()
	count := int64(0)

	resp.Results = func(push func(list.ListResult) bool) {
		for _, item := range items {
			if req.Limit > 0 && count >= req.Limit {
				return
			}
			count++

			result := req.NewListResult(ctx)

			// Build identity: list-config attrs come from config; JSON key attrs from item.
			var identity IPv6LocalPoolIdentity
			identity.Device = config.Device
			identity.Name = types.StringValue(item.Get("id").String())
			result.Diagnostics.Append(result.Identity.Set(ctx, &identity)...)

			// Human-readable display name derived from the first JSON key attribute.
			result.DisplayName = item.Get("id").String()

			// When include_resource is set, populate the full resource state.
			if req.IncludeResource && result.Resource != nil {
				var state IPv6LocalPool
				state.Device = config.Device
				// Set list-config (path-embedded) attrs from config.
				// Set JSON key attrs from the item.
				state.Name = types.StringValue(item.Get("id").String())
				// Populate remaining attributes from the JSON body.
				wrappedJSON := `{"` + lastElement + `":` + item.Raw + `}`
				state.fromBody(ctx, gjson.Parse(wrappedJSON))
				state.Id = types.StringValue(state.getPath())
				result.Diagnostics.Append(result.Resource.Set(ctx, &state)...)
			}

			if !push(result) {
				return
			}
		}
	}
}

// End of section. //template:end listResource
